In [1]:
from keras.models import load_model
from metrics import Pearson
from utils import prepare_data
import tensorflow_probability as tfp
import tensorflow as tf
import numpy as np
from dataloaders import GeneDataLoader

In [2]:
train_data, valid_data, test_data = prepare_data()

In [3]:
model = load_model('/Users/jonasflor/Downloads/Baseline_random.h5',
                   custom_objects={'Pearson': Pearson})

In [4]:
dataloader = GeneDataLoader(test_data, padding_length=train_data['seq'].apply(lambda x: len(x)).max(), shuffle=False, struct=False)

prediction = []
y_test = []

for i, j in dataloader:
    prediction.append(model.predict(i[0]))
    y_test.append(j)

prediction = np.concatenate(prediction)
y_test = np.concatenate(y_test)

1/1 [==============================] - 0s 49ms/step


In [5]:
def pearson_dict(y_true, y_pred):
    y_true_std = tfp.stats.stddev(y_true, sample_axis=0, keepdims=True)
    y_pred_std = tfp.stats.stddev(y_pred, sample_axis=0, keepdims=True)
    
    y_true /= (y_true_std + 1e-3)
    y_pred /= (y_pred_std + 1e-3)
    
    result = tfp.stats.covariance(x=y_true,
                                y=y_pred,
                                event_axis=None,
                                sample_axis=0,
                                keepdims=False)
    res_dict = {}
    res_dict['ERM'] = result[0]
    res_dict['KDEL'] = result[1]
    res_dict['LMA'] = result[2]
    res_dict['MITO'] = result[3]
    res_dict['NES'] = result[4]
    res_dict['NIK'] = result[5]
    res_dict['NLS'] = result[6]
    res_dict['NUCP'] = result[7]
    res_dict['OMM'] = result[8]
    return res_dict

In [6]:
pearson_dict(y_test, prediction)

{'ERM': <tf.Tensor: shape=(), dtype=float32, numpy=-0.1376238>,
 'KDEL': <tf.Tensor: shape=(), dtype=float32, numpy=0.05013642>,
 'LMA': <tf.Tensor: shape=(), dtype=float32, numpy=-0.0050322255>,
 'MITO': <tf.Tensor: shape=(), dtype=float32, numpy=-0.014031444>,
 'NES': <tf.Tensor: shape=(), dtype=float32, numpy=0.013364872>,
 'NIK': <tf.Tensor: shape=(), dtype=float32, numpy=0.10040313>,
 'NLS': <tf.Tensor: shape=(), dtype=float32, numpy=0.09802337>,
 'NUCP': <tf.Tensor: shape=(), dtype=float32, numpy=0.116804175>,
 'OMM': <tf.Tensor: shape=(), dtype=float32, numpy=0.08749543>}